---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zengbin.
--- DateTime: 2023/9/28 19:50
---
---在 Lua 中，函数是被看作是"第一类值（First-Class Value）"，函数可以存在变量里:
function factorial1(n)
    if n == 0 then
        return 1
    else
        return n * factorial1(n - 1)
    end
end
print(factorial1(5))
factorial2 = factorial1
print(factorial2(5))
---function 可以以匿名函数（anonymous function）的方式通过参数传递:
function testFun(tab,fun)
    for k ,v in pairs(tab) do
        print(fun(k,v));
    end
end

tab={key1="val1",key2="val2"};
testFun(tab,
        function(key,val)--匿名函数
            return key.."="..val;
        end
);

function testVar()
    var = 100
end
testVar()
print(var)

print("------------print function-------------")
local myprint = function(value)
    print("打印一个值" .. value)
end
local function add(param1,param2,printFunction)
    local result = param1+param2
    printFunction(result)
end
myprint(10)
add(1,3, myprint)

local s,e = string.find("www.baidu123.com", "baidu12")
print(s,e)

local function get_max_val(tab)
    local max_index =1
    local max_value =tab[max_index]
    for i,var in ipairs(tab) do
        if(var > max_value) then
            max_index = i
            max_value = var
        end
    end
    return max_index,max_value
end

print(get_max_val({1,12,34,54,10}))

local function average(...)
    result = 0
    local arg={...}    --> arg 为一个表，局部变量
    for i,v in ipairs(arg) do
        result = result + v
    end
    print("总共传入 " .. #arg .. " 个数")
    return result/#arg
end

print("平均值为",average(10,5,3,4,5,6))

do
    function foo(...)
        for i = 1, select('#', ...) do  -->获取参数总数
            local arg = select(i, ...); -->读取参数，arg 对应的是右边变量列表的第一个参数
            print("arg", arg);
        end
    end
    foo(1, 2, 3, 4);
end
