---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zengbin.
--- DateTime: 2023/10/2 10:11
---
if 0 then
    print("0 is true")
else
    print("0 is not true")
end

if false or nil then
    print("xxxxxx")
else
    print("yyyyyy")
end

if false or 0 then
    print("000000")
else
    print("111111")
end

if nil and 0 then
    print("nnnnnnn")
else
    print("fffffff")
end