---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zengbin.
--- DateTime: 2023/10/3 09:10
---
print(5/2)
print(5//2)
print(10/3)
print(10//3)

local var = "hello"
print("length '#var'" .. #var)