---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zengbin.
--- DateTime: 2023/10/3 09:25
---
string1 = "Lua"
print("\"字符串 1 是\"",string1)
string2 = 'runoob.com'
print("字符串 2 是",string2)

string3 = [["Lua 教程"]]
print("字符串 3 是",string3)

local var = "hello,世界"
print(string.len(var))
print(utf8.len(var))
print(#var)

local subStr = "aaaatteee";
tab = {}
tab = string.gsub(subStr, "e", "x",2)
print(string.gsub(subStr, "e", "x",2))
print(tab)

print(string.find("hello lua users", "lua", 1))
print(string.find("hello lua users", "a", -1))

print(string.reverse("Lua"))

print(string.format("hello %d", 666))

print(string.rep("abcd",3))