---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zengbin.
--- DateTime: 2023/9/28 20:11
---

a = 5               -- 全局变量
local b = 5         -- 局部变量

function joke()
    c = 5           -- 全局变量
    local d = 6     -- 局部变量
end

joke()
print(c,d)          --> 5 nil

do
    local a = 6     -- 局部变量
    b = 6           -- 对局部变量重新赋值
    print(a,b);     --> 6 6
end

print(a,b)      --> 5 6

local flag = nil
print("xxx" .. tostring(flag))

local userName = "张三"
local mobile = "18867102687"
local insertSql = [[insert into f_user(user_name,mobile,password,create_time) values (]] .. userName .. [[,]] .. mobile ..  [[, '111111', now())]]
print(insertSql)

tab = {insert_id=4073}
print(tab["insert_id"])