---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zengbin.
--- DateTime: 2023/10/2 09:31
---
local tab_list = {[1]="a",[2]="b",[3]="c"}
print("------------for pairs------------")
for i,v in pairs(tab_list) do    -- pairs是无序的，不会碰到nil中断
    print(i .. "=" .. tab_list[i])
end
print("------------for ipairs------------")
for i,v in ipairs(tab_list) do   -- ipairs是有序的，会碰到nil中断，因为数组下标为2不存在值中断
    print(i .. "=" .. tab_list[i])
end
print("------------do while------------")
local sum = 1
while(sum < 4) do
    print(sum)
    sum = sum + 1
end
print("------------repeat until------------")
local sum2 = 10
repeat
    print("sum2=" .. sum2)
    sum2 = sum2+1
until(sum2 > 15)
