---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zengbin.
--- DateTime: 2023/10/31 08:52
---
function get_from_cache(key)
    local my_cache = ngx.shared.my_cache
    local value = my_cache:get(key)
    return value
end

function set_to_cache(key,value)
    local my_cache = ngx.shared.my_cache
    local res = my_cache:set(key,value)
    return res
end

local key = ngx.req.get_uri_args()["key"]
local value = ngx.req.get_uri_args()["value"]

local res = set_to_cache(key,value)
ngx.say("response=", res)

local cache_val = get_from_cache(key)

ngx.say("value=", cache_val)