---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zengbin.
--- DateTime: 2023/10/31 19:06
---
local lrucache = require "resty.lrucache"
local c = lrucache.new(200)    ---allow up to 200 items in the cache
if not c then
    return error("failed to create the cache:" .. (err or "unknown"))
end
res1,err1,log1 = c:set("dog",32)
ngx.say("set:",res1,err1,log1)
res2,err2,log2 = c:get("dog")
ngx.say("get:",res2,err2,log2)