---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zengbin.
--- DateTime: 2023/10/16 08:27
---
---加载json相关包
local cjson = require "cjson"
---加载相关驱动
local mysql = require "resty.mysql"
---配置连接信息
local props = {
    host = "127.0.0.1",
    port = 3306,
    database = "food",
    user = "root",
    password = "root"
}
---创建连接、设置超时时间、编码格式
local db = mysql:new()
db:set_timeout(10000)
db:connect(props)
db:query("SET NAMES utf8")
---插入数据
local userName = ngx.req.get_uri_args()["userName"]
if userName == nil then
    userName = "张大彪"
end
local mobile = ngx.req.get_uri_args()["mobile"]
if mobile == nil then
    mobile = "111111111"
end
local insertSql = string.format("insert into f_user(user_name,mobile,password,create_time) values ('%s','%s','111111',now())", userName, mobile)
---执行sql语句
local res,err,errno,sqlstate = db:query(insertSql)
if not res then
    ngx.say("insert table error:",err,",errno:",errno,",sqlstate:",sqlstate)
    db:close()
    return
end
ngx.log(ngx.INFO, "insert table res:", cjson.encode(res))   ---打印调试日志

---SQL语句
local uid = res["insert_id"]
if not uid then
    ngx.say("uid can not be null")
    return
end
local sql = "select * from f_user where uid = " .. uid
---执行sql语句
local result = db:query(sql)
---关闭连接
db:close()
---响应数据json
ngx.say(cjson.encode(result))
return
