---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zengbin.
--- DateTime: 2023/10/31 20:36
---

local function print_table(t)
    local function parse_array(key, tab)
        local str = ''

        for _, v in pairs(tab) do
            str = str .. key .. ' ' .. v .. '\r\n'
        end

        return str
    end

    local str = ''
    for k,v in pairs(t) do
        if type(v) == 'table' then
            str = str .. parse_array(k,v)
        else
            str = str .. k .. ' ' .. (v) .. '\r\n'
        end
    end

    return str
end

--- 获取头信息
--- local headers = ngx.req.get_headers(0,true)

--- 修改头信息
ngx.req.set_header('Foo', 'bar')
local res = ngx.location.capture('/localCache')

if res.status == ngx.HTTP_OK then
    ngx.say(res.body)
else
    ngx.exit(res.status)
end

ngx.say(print_table(headers))
