---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zengbin.
--- DateTime: 2023/10/31 19:22
---
local redis = require "resty.redis"

local red = redis:new()

function set_to_cache(key,value,exptime)
    if not exptime then
        exptime = 0
    end
    local my_cache = ngx.shared.my_cache
    local succ,err,forcible = my_cache:set(key,value,exptime)
    return succ
end

function get_from_cache(key)
    local my_cache = ngx.shared.my_cache
    local value = my_cache:get(key)
    if not value then
        value = get_from_redis(key)
        set_to_cache(key,value)
    end
    return value
end

function get_from_redis(key)
    local res,err = red:get(key)
    if res then
        return "yes"
    else
        return "no"
    end
end

local res = get_from_redis("dog")
ngx.say(res)
