---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zengbin.
--- DateTime: 2023/11/9 20:35
---通过闭包的方式实现面向对象
---封装
function People(name)
    local self = {}
    local function init()
        self.name = name
    end

    self.sayHi = function()
        print("Hi " .. self.name)
    end

    init()
    return self
end

local p = People("zhangsan")
p:sayHi()
---继承
function Man(name)
    local self = People(name)

    self.sayHello = function()
        print("Hello " .. self.name)
    end

    return self
end

local m = Man("lisi")
m:sayHello()
m:sayHi()