---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zengbin.
--- DateTime: 2023/11/9 20:49
---通过复制表的方式实现面向对象
function clone(tab)
    local ins = {}
    for key,var in pairs(tab) do
        ins[key] = var
    end
    return ins
end

function copy(dist,tab)
    for k, v in pairs(tab) do
        dist[k] = v
    end
end

People = {}

People.sayHi = function()
    print("People say hi")
end

function People.sayHi2(self)
    print("People say hi:" .. self.name)
end

People.new = function(name)
    local self = clone(People)
    self.name = name

    return self
end
---对象封装创建
local p = clone(People)
print("------------对象的封装------------")
p:sayHi()
---对象封装创建，携带参数
local pp = People.new("zhangsan")
print("------------对象的封装，携带参数------------")
pp.sayHi()
pp:sayHi2()
---类的继承
Man = {}
Man.new = function(name)
    local self = People.new(name)
    copy(self, Man)
    return self
end

Man.sayHello = function()
    print("Man say hello")
end

---方法的重写
Man.sayHi = function(self)
    print("Man say hi " .. self.name)
end

local m = Man.new("lisi")
print("------------对象的继承------------")
m:sayHello()
m:sayHi2()
print("------------方法的重写------------")
m:sayHi()
