---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zengbin.
--- DateTime: 2023/10/12 18:49
---local luasql = require "resty.mysql"
---local socket = require "socket"
---加载json相关包
local cjson = require "cjson"
---加载相关驱动
local luasql = require "luasql.mysql"
---构建环境对象
local env = luasql.mysql()
---连接mysql
local conn,connErrorInfo = env:connect("food","root","root","127.0.0.1",3306)
if nil~=connErrorInfo then
    print(conn,connErrorInfo)
end
---设置数据库编码格式
conn:execute"SET NAMES UTF8"
---创建json实例
local jsonObj = cjson.new()
---文件对象的创建
local file = io.open("userInfo.txt","w+");
---1.先执行数据库清理
local status,errorInfo = conn:execute([[DELETE FROM f_user]])
if nil~=errorInfo then
    print(status,errorInfo)
end
---2.再执行数据库批量插入
for i=1,6 do
    local status,errorInfo = conn:execute([[INSERT INTO f_user(user_name,mobile,password,create_time) values ('xxxx','1887900','111111',now())]])
    if nil~=errorInfo then
        print(status,errorInfo)
    end
end
---3.再执行数据库查询、打印、插入文件等操作
local cur,errorInfo = conn:execute("select * from f_user")
if nil~=errorInfo then
    print(cur,errorInfo)
end
local row = cur:fetch({}, "a")
while row do
    local userInfo = {uid=row.uid, userName=row.user_name, mobile=row.mobile, password=row.password, createTime=row.create_time}
    local userJson = jsonObj.encode(userInfo)
    print("用户信息: " .. userJson)
    file:write(userJson .. "\n")
    row = cur:fetch(row, "a")
end
---关闭游标
cur:close()
---关闭数据库连接
conn:close()
---关闭数据库环境
env:close()